### ISSUE TITLE
Npm rund dev error

### ISSUE THREAD

**Issue by Schwenniii** [enso-ui/tables#24]
i update from
"@enso-ui/directives": "^1.0.15",
    "@enso-ui/dropdown": "1.1.10",
    "@enso-ui/loader": "1.0.13",
    "@enso-ui/modal": "1.0.18",
    "@enso-ui/tables": "1.4.23",
    "@enso-ui/toastr": "1.0.33",
"bulma": "^0.7.5",

to the last Versions
"@enso-ui/directives": "^1.0.16",
    "@enso-ui/dropdown": "^2.0.1",
    "@enso-ui/loader": "^2.0.0",
    "@enso-ui/modal": "^2.0.1",
    "@enso-ui/tables": "^2.0.0",
    "@enso-ui/toastr": "^2.1.0",
"bulma": "^0.7.5",

After Update npm run dev returns to errono 2

### Actual behavior
./node_modules/@enso-ui/tables/src/bulma/parts/top/Filters.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@enso-ui/tables/src/bulma/parts/top/Filters.vue?vue&type=script&l
ang=js&) 82:47
Module parse failed: Unexpected token (82:47)
File was processed with these loaders:
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     computed: {
|         custom() {
>             return this.state.template.filters?.map(filter => ({
|                 ...filter, component: this.component(filter),
|             })) || [];

**Comment by raftx24** [comment]
Hi, we used `Optional chaining`, you need to config your babel.

**Comment by henryejemuta** [comment]
@raftx24 I'm currently stuck with the same error I have included:
````
mix.babelConfig({
    "presets": [
        "@babel/preset-env"
    ],
    "plugins": []
});
````

to webpack.mix.js configuration file, but still the same error... can you point me to a resource or help out with the babel configuration.

@Schwenniii how did you resolve this?
