### ISSUE TITLE
Bug with range filter and date picker

### ISSUE THREAD

**Issue by nesumneno** [enso-ui/tables#27]
This is  a **bug**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

Hi,
I posted recently about an issue with the date pickers. 
https://github.com/laravel-enso/tables/issues/204

There is still a problem but the behavior is slightly different.

There are two problems.

1. Sometimes when you click fast on the input the menu closes again.
2. The range picker is not working and throws an error in the console log

PS:
There is also an error when you select a date but on local I don't get that.

### Steps to Reproduce
1. Select Created At filter on tutorials
2. Select interval
3. Click outside menu and close the box (sometimes it closes by itself)
4. Open Created At filter again

### Expected behavior
Filters data by date interval

### Actual behavior
Not working

![enso-error-1](https://user-images.githubusercontent.com/11031695/93667147-42204d00-fa8c-11ea-9e28-be8e80710ee8.jpg)

**Comment by raftx24** [comment]
Hi @nesumneno 
I fixed the range filter bug, But I couldn't reproduce the first bug(`Sometimes when you click fast on the input the menu closes again.`)!
